### ISSUE TITLE
Python version >=3.8

### ISSUE THREAD

**Issue by NicoleRichards1998** [diovisgood/intraday#1]
Hi, thank you so much for creating this intraday environment. I am trying to run it on google colab, but I'm running into an error because the intraday package requires Python 3.7.12 but colab needs it to be >=3.8. I've considered just taking my colab down to 3.7 version of python, but then all my other code fails because its made for >=3.8. Is there some easy fix to take the environment to a newer python version?

**Comment by diovisgood** [comment]
Hi, Nocole
This is strange, because in the file setup.py there is a condition: "python_requires='>=3.8'"
Could you please provide some code, how do you load and run this package in colab?

**Comment by NicoleRichards1998** [comment]
Ooh okay then I might have misunderstood the error. here is a screenshot of what I'm getting:
![Screen Shot 2022-02-09 at 10 25 08 AM](https://user-images.githubusercontent.com/97527265/153155472-07c50824-76f1-489d-8abd-fea0084ee6da.png)

**Comment by diovisgood** [comment]
Now I see. Colab has python version 3.7.12, while I specified required version to be >= 3.8.
![2022-02-09_13-32-11](https://user-images.githubusercontent.com/6111420/153156472-13e071bd-4346-466a-a08d-8510b2972aca.png)

I can easily change this line to >= 3.7
Though I'm a little busy now and I don't have time to fully test it under python 3.7.
I hope, you'll test it and everything will work fine.

**Comment by diovisgood** [comment]
I changed required version, so you can try to update the package

**Comment by diovisgood** [comment]
Changed requirements.
